### ISSUE TITLE
Can’t figure out how to run it as a gem

### ISSUE THREAD

**Issue by pinzonjulian** [fernandes/arara#15]
Hey! First, I'd like to congratulate you for this project. It's absolutely amazing. The attention to detail is great. 

I'd like to run this as a gem inside a project to be able to understand all that it does and how it does it. I'm specially interested in understanding how forms work and how well they play with things like error handling for example. 

My main problems when trying to run this in a new rails app are:
- How do I get the styles inside my app's style sheet (asset pipeline, webpacker?)
- How do I include the JS for it?

**Comment by fernandes** [comment]
hello @pinzonjulian ,

thanks for the interest on this gem 😄 

the usage has no _special_ instructions, I'm gonna write it down quickly for you here and then I add into the read (I just realized there's nothing about there 😬 )

in your Gemfile

> gem 'arara'

to add in your package.json, run

> yarn add arara (npm install arara)

and the `@material` dependencies you want to use (also stimulus is a must)

you can check all the dependencies into the [test/dummy/package.json](https://github.com/fernandes/arara/blob/75e6290d10167a1699ac83a06e7d1ebf5f4e9fc5/test/dummy/package.json#L5-L33)

if you current project still doesn't use `ActionView::Component`, then add into your `config/application.rb`

```ruby
require 'action_view/component/railtie'
```

after that you can call the components in any erb file:

```ruby
%= render(Arara::TextFieldComponent, label: "Standard", class: "text-field", id: "text-field-filled", helper_text: "Helper Text") %>
```

take a look on [test/dummy/app/views/pages](https://github.com/fernandes/arara/tree/master/test/dummy/app/views/pages) for more examples (the cool idea is to run arara locally according to [README](https://github.com/fernandes/arara#demo) so you can see it in action)

after that you are ready to use arara controllers as it's being used into [test/dummy/app/javascript/controllers/index.js](https://github.com/fernandes/arara/blob/master/test/dummy/app/javascript/controllers/index.js)

and import the css like [app/javascript/styles/dummy.scss](https://github.com/fernandes/arara/blob/master/test/dummy/app/javascript/styles/dummy.scss#L1)

I'm still thinking if compile the scss is the right approach, maybe in the future would be interesting to provide using already compiled css from a CDN or compile yourself the scss (both approaches has its pros/cons)

Anyway, I think I could _brain dump_ all the information, please let me know if that works for you

all the best 🍻

**Comment by pinzonjulian** [comment]
Hey Celso! Thanks for your answer. 

I hadn't had time to dive into this in the past few weeks but I'm starting to do it again. I'll keep you posted and get back to you with any other questions that pop to mind.

**Comment by pinzonjulian** [comment]
I've reached a bit of a blocker when it comes to styling.

Here's what I've done so far:

1. Started new rails app
2. Installed stimulus
3. Added arara and view component to the gemfile
```ruby
#gemfile
gem "actionview-component", "~> 1"
gem 'arara'
```
4. Ran `bundle install to install the gems`
5. Ran `yarn add arara`
6. Copied all material dependencies from the gem's `package.json`
7. Added `require 'action_view/component/railtie'` to `application.rb`
8. Created a sample controller `rails g controller static home`
9. Added controller action as root of the app 
```ruby
#routes.rb
root to: 'static#home'
```
10. Added a sample component to the template
```erb
# home.html.erb
<%= render(Arara::TextFieldComponent, label: "Standard", class: "text-field", id: "text-field-filled", helper_text: "Helper Text") %>
```
11. Started the server `rails s`
12. Visited `localhost:3000`
13. Component renders with no styles (which is kind of obvious because I haven't imported any of the styles anywhere)

And here I got stuck. 

Where do I import styles from? I'm not very experienced with webpacker so it might be a bit of ignorance from my part but after trying for a while I couldn't figure it out. Could you give me a hand please?

I've added my progress to this repo:
https://github.com/pinzonjulian/exploring_arara

**Comment by fernandes** [comment]
hey @pinzonjulian no worries

you need to import arara css into your webpacker and then add it on your layout

here are the [webpacker docs](https://github.com/rails/webpacker/blob/master/docs/css.md) and how I [added the css into test dummy app](https://github.com/fernandes/arara/blob/master/test/dummy/app/javascript/styles/dummy.scss#L1)

does it helps you? best!

**Comment by pinzonjulian** [comment]
Hey Celso
I'd tried that before but it didn't work. If I do this:
```
@import "arara/scss/arara.scss";
```
Rails can't resolve that path because it's pointing towards:
```
arara (the gem itself)
  - app
    - assets
      - stylehseets
        - arara
          - scss (not found)
            - arara.scss (not found)
```
However, the file I need to import lives in the javascript folder in the gem's app folder. So I can try to traverse backwards from there to where the file actually is:
```
@import "arara/../../../javascript/arara/scss/arara.scss"
```

but I get this error: 
```
File to import not found or unreadable: arara/../../../javascript/arara/scss/arara.scss.
```

I tried importing the `@material` dependencies individually but that lead me down another never ending rabbit hole.

So I'm still stuck. 

Have you tried to install this as a gem yourself on a separate project before? did you run into any of these issues?

**Comment by pinzonjulian** [comment]
On a separate note, I guess I've never told you why I'm diving into this project so much.

I feel that there's a need (a very dire one) for these kinds of libraries in the Rails community. Component libraries you can just plug in very easily and have the same visual output you get when using, for example, "material-ui". I was meaning to build the material spec in view component myself but someone told me you had already done it and I was super excited to see it. I was even more excited when I saw how you built the components and the architecture of it; it's really well built.

However, I haven't been able to use it and explore it fully due to the lack of documentation and examples. The dummy app does a good job at showcasing components in isolation but after seeing the code, there's a ton that's not covered in the dummy app like `FormBuilder` for example (which is the cherry on top in my opinion).

I'd really like for this project to see the light as a library for the wider rails community and I'd be willing to help you maintain it. If it's something you don't want to do (based on your comments on the other issue opened previously), is it ok if I fork this project and either maintain this version or create a new one based on your findings?

**Comment by fernandes** [comment]
hello @pinzonjulian 

> Have you tried to install this as a gem yourself on a separate project before?

yes, this was extracted from a system in production 😉 

> did you run into any of these issues?

no I haven't

> but someone told me you had already done it

does someone else knows about this project? cool! 😄 

about lack of documentation and examples, this is an open source project, I'm sharing the code that took (literally) hours and hours of work, sorry about this lack of docs/examples, but arara doesn't pay any cent, so I'm focused on my daily work that pays the bills

in the other hand, we can explore together, and I'm always open to any contribution, any PR that can help improve it 😄 

> and I'd be willing to help you maintain it

awesome, thank you very much! 🙇 

> If it's something you don't want to do (based on your comments on the other issue opened previously)

I just mentioned that I don't wanna extract into individuals stimulus controllers and maintain them separately , about arara I'm all in, specially because that system in production depends on it hahaha I'm also working on migrating to mdc version 7 (still experimenting with it)

if you wanna

## Use MDC

Add

```html
<link rel="stylesheet" href="https://unpkg.com/material-components-web@4.0.0/dist/material-components-web.min.css">
```

to your rails layout

## Compile MDC

in your `exploring_arara` project, on [layout](https://github.com/pinzonjulian/exploring_arara/blob/master/app/views/layouts/application.html.erb#L8) you need to use `stylesheet_pack_tag` as per [webpacker docs](https://github.com/rails/webpacker/blob/master/docs/css.md)

and in your [application pack](https://github.com/pinzonjulian/exploring_arara/blob/master/app/javascript/packs/application.js) you need to:

```js
require "./application.scss"
```

then in your application.scss

```scss
// Customization
// $mdc-theme-primary: #2196F3;
// $mdc-theme-primary: #6200ee;
// $mdc-theme-secondary: #ffc107;

// Material Design
@import "@material/typography/mdc-typography";
@import "@material/ripple/mdc-ripple";
@import "@material/top-app-bar/mdc-top-app-bar";

@import "@material/form-field/mdc-form-field";
@import "@material/button/mdc-button";
@import "@material/card/mdc-card";
@import "@material/checkbox/mdc-checkbox";
@import "@material/icon-button/mdc-icon-button";
@import "@material/chips/mdc-chips";
@import "@material/data-table/mdc-data-table"; // needs checkbox
@import "@material/dialog/mdc-dialog";
@import "@material/elevation/mdc-elevation";
@import "@material/fab/mdc-fab";
@import "@material/image-list/mdc-image-list";
@import "@material/layout-grid/mdc-layout-grid";
@import "@material/drawer/mdc-drawer";
@import "@material/list/mdc-list";
@import "@material/linear-progress/mdc-linear-progress";
@import "@material/menu-surface/mdc-menu-surface"; //needs list
@import "@material/menu/mdc-menu"; //needs list
@import "@material/radio/mdc-radio"; // needs form field
@import "@material/select/mdc-select"; // needs list, menu-surface, menu
@import "@material/slider/mdc-slider";
@import "@material/snackbar/mdc-snackbar";
@import "@material/switch/mdc-switch";

@import "@material/tab-bar/mdc-tab-bar";
@import "@material/tab-scroller/mdc-tab-scroller";
@import "@material/tab-indicator/mdc-tab-indicator";
@import "@material/tab/mdc-tab";

@import "@material/textfield/mdc-text-field";

// any css comes here
```

ps: keep the order to make mdc happy

**Comment by fernandes** [comment]
Anyone reading this, check https://github.com/pinzonjulian/exploring_arara/pull/1 😉
